//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSignupLoginMVC.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class User
    {
        public int USR_ID { get; set; }
        
        public string USR_Email { get; set; }
        public string USR_Password { get; set; }
        public string USR_Phone { get; set; }

        [Required(ErrorMessage = "this field is required")]
        [Display(Name = "username")]
        public string USR_Name { get; set; }
        public string USR_NID { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime USR_BDate { get; set; }
        public string USR_Gender { get; set; }

        [Compare("USR_Password", ErrorMessage = "the password didn't match")]
        public string repasssword { get; set; }

    }
}
